require 'config.options'
require 'config.languages'
require 'config.keymaps'
require 'config.autocmds'

-- Plugin imports
require 'config.spec'
spec 'plugins.colors'
spec 'plugins.languages'
spec 'plugins.conform'
-- spec 'plugins.copilot'
spec 'plugins.dashboard-vim'
spec 'plugins.dressing'
spec 'plugins.neo-tree'
spec 'plugins.neotest'
spec 'plugins.nvim-cmp'
spec 'plugins.nvim-dap'
spec 'plugins.nvim-lspconfig'
spec 'plugins.telescope'
spec 'plugins.treesitter'
spec 'plugins.vim-tmux-navigator'
spec 'plugins.which-key'
spec 'plugins.zoomwintab'
require 'config.lazy'

require 'config.colors'
